global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: gameperf
    static_configs:
      - targets: ["gameperf-host:9100"]
        labels:
          instance: "local"
